// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDrive_API.Data_Access;

#nullable disable

namespace MyDrive_API.Migrations
{
    [DbContext(typeof(MyDriveDBContext))]
    [Migration("20240928101813_create_Filestorage_table")]
    partial class create_Filestorage_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyDrive_API.Models.FileFolder.FileStorageDetails", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(16)")
                        .HasColumnName("Id");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Data");

                    b.HasKey("Id");

                    b.ToTable("FileStorageInfos");
                });

            modelBuilder.Entity("MyDrive_API.Models.User.UserDetails", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("UserId");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Password");

                    b.Property<byte[]>("Profile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("Profile");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
